version: "3.1"
services:
  app:
    build:
      dockerfile: Dockerfile
    
    container_name: lstgrd-app
    restart: unless-stopped
    
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    
    ports:
      - 9200:9200
      

