# Generated by Django 4.2.1 on 2023-07-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=262, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 12, 58, 18, 81848))),
                ('class_name', models.CharField(blank=True, max_length=700, null=True)),
                ('class_number', models.IntegerField()),
                ('keycode', models.CharField(max_length=4)),
                ('books', models.ManyToManyField(blank=True, null=True, to='identifier.book')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 12, 58, 18, 85397))),
                ('logo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('city', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=100)),
                ('classesq', models.ManyToManyField(blank=True, null=True, to='identifier.classes')),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'ordering': ['created_at'],
            },
        ),
    ]
