# Generated by Django 4.2.1 on 2023-07-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 12, 58, 49, 842440)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 12, 58, 49, 848167)),
        ),
    ]
