# Generated by Django 4.2.1 on 2023-07-23 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identifier', '0003_alter_classes_created_at_alter_school_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 17, 21, 33, 274007)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 17, 21, 33, 276342)),
        ),
        migrations.CreateModel(
            name='SuggestedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory', models.TextField(blank=True)),
                ('books', models.ManyToManyField(blank=True, to='identifier.book', verbose_name='Books')),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suggested Books',
            },
        ),
    ]
