# Generated by Django 4.2.1 on 2023-08-09 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0007_book_pdf_alter_classes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 52, 23, 508279)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 52, 23, 510103)),
        ),
    ]
