# Generated by Django 4.2.1 on 2023-08-09 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0009_alter_classes_created_at_alter_school_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('UN', 'Unspecified'), ('TU', 'Tutorial'), ('RS', 'Research'), ('RW', 'Review')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='suggestedbooks',
            name='type',
            field=models.CharField(choices=[('UN', 'Unspecified'), ('TU', 'Tutorial'), ('RS', 'Research'), ('RW', 'Review')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 14, 33, 29, 816406)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 14, 33, 29, 818034)),
        ),
    ]
