# Generated by Django 4.2.1 on 2023-08-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0010_book_type_suggestedbooks_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 34, 38, 235237)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 34, 38, 237307)),
        ),
    ]
