# Generated by Django 4.2.1 on 2023-08-09 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0012_alter_classes_created_at_alter_school_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 43, 41, 859783)),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 43, 41, 861229)),
        ),
    ]
